library(censusapi) 
library(tidyverse)
library(dplyr)
library(extrafont)
library(scales)
library(directlabels)
library(grid)
library(here)
library(knitr)
library(readxl)
library(xfun)

#library(xlsx)

#load("inputs/allparishesRawx.RData")

library(AzureAuth) ## to connect with credentials
library(AzureStor) ## to access the stored data

## install azure cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
## sign in to Azure using your AAD un/pw in the terminal/commandline: az login 
## get token in terminal/commandline: az account get-access-token --resource https://datacenterdc2datalake.blob.core.windows.net/

### define your token 
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL2RhdGFjZW50ZXJkYzJkYXRhbGFrZS5ibG9iLmNvcmUud2luZG93cy5uZXQvIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2LyIsImlhdCI6MTcyMzQ5NDMzNSwibmJmIjoxNzIzNDk0MzM1LCJleHAiOjE3MjM0OTg5NTksImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WEFBQUFlMGRFTndCMnc5TnBxM2hyVEZ6Z1lMUUNhaG13YWVsL2xtb3RKSkd0YVZrNk95UnBNQzZnQ01jMTI0b2dqbHZoUWdoaEo2MzFaNHAyWnR3NmZlV0lmQ2hFVFZEeHVQb0pQc1BhQk4vYzAxcz0iLCJhbXIiOlsicHdkIiwicnNhIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZGV2aWNlaWQiOiJiNWRjNGRlYS1lODE0LTQ4MTAtYWUyYS1lMzcyODc1ZjA1NTUiLCJmYW1pbHlfbmFtZSI6IlRvbWxpbiIsImdpdmVuX25hbWUiOiJIYWxlaWdoIiwiZ3JvdXBzIjpbIjc3MmM0NzFjLWU1ZDMtNGViNC1hNmExLWRmOWRlZjk2MWZlYyIsImFkMDk0OGFjLWFmNjgtNDQ5NS04Y2NkLTQxNGMzY2NmZjM3MyJdLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyMDguMTE3LjIwNy4xMjIiLCJuYW1lIjoiSGFsZWlnaCBUb21saW4iLCJvaWQiOiIxODk4MTI1My00MTY0LTQ5MjAtYTFiOS0xOWIwNjcxODA1ZjEiLCJwdWlkIjoiMTAwMzIwMDIxRUUwMzY0NyIsInB3ZF91cmwiOiJodHRwczovL3BvcnRhbC5taWNyb3NvZnRvbmxpbmUuY29tL0NoYW5nZVBhc3N3b3JkLmFzcHgiLCJyaCI6IjAuQVNrQXVoLWNkQ2tzRDBxSDJvZDJSN3U5aG9HbUJ1VFU4NmhDa0xiQ3NDbEpldkVwQUg4LiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ino5TXFwRHlnUTFvcmFFZ0d0dFlRN3p5djRzMVU5amNwdFB3NS1CSjFmT2ciLCJ0aWQiOiI3NDljMWZiYS0yYzI5LTRhMGYtODdkYS04Nzc2NDdiYmJkODYiLCJ1bmlxdWVfbmFtZSI6IkhhbGVpZ2h0QGRhdGFjZW50ZXJyZXNlYXJjaC5vcmciLCJ1cG4iOiJIYWxlaWdodEBkYXRhY2VudGVycmVzZWFyY2gub3JnIiwidXRpIjoiYk41bXpsODVhVTZCME1HR3phWjhBQSIsInZlciI6IjEuMCIsInhtc19pZHJlbCI6IjEgMTYifQ.Mz6Ut8RNVK3ciRmWKtF1m-82CpTFhu9ggoVrjC3_jYo-2MtKbp9u04AVIYQuQushZlCyu0Hc9ipX_DCljRz684yag4J37VukvnAySrJgNmkMR4TteV52RnZ1dX9pp3IOEWkLE5VTNUrgnomSiaOcvt5xFPClfLEHsxcGQgPgKuo0zcSgoRD1w8XpjUx4CgRvz35YLodDj19chMcxPSL9RuOtTXR7PLsgu5-rKREz01Zjz4cta3SZhRak-y7HyAo6TjUqe9ktvblvkMY3VEz828xcEQSHb1AxZZe2uHxkbK05cTG3nnmcdW-axoU0LqlhRUGORDQjw9jX1kGmjcPUnw"
ad_endp_tok2 <- storage_endpoint("https://datacenterdc2datalake.blob.core.windows.net/", token=token) ## again, the rsource/URL

## Connections to some most-used containers.
cont_proj <- storage_container(ad_endp_tok2, "project") 
#df <- storage_read_csv(cont_proj, "who_lives/2022/inputs/WhoLives_longer.csv") %>% select(-1) #make sure this is updated within datalake - querying_WhoLives_factconsolidated

#to write back to azure, use storage_write_csv(df, cont_proj, "who_lives/2022/outputs/file_name")
