library(censusapi) 
library(tidyverse)
library(dplyr)
library(extrafont)
library(scales)
library(directlabels)
library(grid)
library(here)
library(knitr)
library(readxl)
library(xfun)

#library(xlsx)

#load("inputs/allparishesRawx.RData")

library(AzureAuth) ## to connect with credentials
library(AzureStor) ## to access the stored data

## install azure cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
## sign in to Azure using your AAD un/pw in the terminal/commandline: az login 
## get token in terminal/commandline: az account get-access-token --resource https://datacenterdc2datalake.blob.core.windows.net/

### define your token 
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2RhdGFjZW50ZXJkYzJkYXRhbGFrZS5ibG9iLmNvcmUud2luZG93cy5uZXQvIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2LyIsImlhdCI6MTY5MDgyMDY3MSwibmJmIjoxNjkwODIwNjcxLCJleHAiOjE2OTA4MjYyMDcsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84VUFBQUFLalpQaTZuN1pZNTF2UHB5OEgvZDhyeVZqSm9oYzF0VGN0REVLUnpMRlR6bVpLb20vVEtIMDIvQWZYcjVoR1JWRkRKQjJJcTJFTnlZTUtZdkMwcWdvYkEyVHlZa09QNzhGeHB6eVJnd0w1WT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJUb21saW4iLCJnaXZlbl9uYW1lIjoiSGFsZWlnaCIsImdyb3VwcyI6WyI3NzJjNDcxYy1lNWQzLTRlYjQtYTZhMS1kZjlkZWY5NjFmZWMiLCJhZDA5NDhhYy1hZjY4LTQ0OTUtOGNjZC00MTRjM2NjZmYzNzMiXSwiaXBhZGRyIjoiMjA4LjExNy4yMDcuMTIyIiwibmFtZSI6IkhhbGVpZ2ggVG9tbGluIiwib2lkIjoiMTg5ODEyNTMtNDE2NC00OTIwLWExYjktMTliMDY3MTgwNWYxIiwicHVpZCI6IjEwMDMyMDAyMUVFMDM2NDciLCJyaCI6IjAuQVNrQXVoLWNkQ2tzRDBxSDJvZDJSN3U5aG9HbUJ1VFU4NmhDa0xiQ3NDbEpldkVwQUg4LiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ino5TXFwRHlnUTFvcmFFZ0d0dFlRN3p5djRzMVU5amNwdFB3NS1CSjFmT2ciLCJ0aWQiOiI3NDljMWZiYS0yYzI5LTRhMGYtODdkYS04Nzc2NDdiYmJkODYiLCJ1bmlxdWVfbmFtZSI6IkhhbGVpZ2h0QGRhdGFjZW50ZXJyZXNlYXJjaC5vcmciLCJ1cG4iOiJIYWxlaWdodEBkYXRhY2VudGVycmVzZWFyY2gub3JnIiwidXRpIjoiSnktUUljeWNNVXVMczJWZnVSRjRBQSIsInZlciI6IjEuMCJ9.j0F8ba7-IsKwtrturiChl2QLbja7LRQdk8rdqfg_XVYhUBPrybGfu3frA8VRnC_m9hs84J_wHmCpYYoZH9y-ABrI9uDT619EPyr0p2zr1peY5GiYyvaYI_9yNRJUASPQiLUJdRJD61ZvFbGkX76EEUWGr5BsqARDqH6467Hn9aS4cqcFZ55t3_SxOl9YUX010p901Kx8SCXMi4ovoTBZHyJWB1zItUzzJLvKUdW2da5Ioe1o0vCMr_cIoMcLlcig_46NMDSVd9HGahw1SdHWvwt-UBwVQNUbFq2qvJUQ0o2eCgePcGnXBB0rjRtaoc7VbpukJzvADsEEu_fxQYeO4A"
# delete token before pushing to github

ad_endp_tok2 <- storage_endpoint("https://datacenterdc2datalake.blob.core.windows.net/", token=token) ## again, the rsource/URL

## Connections to some most-used containers.
cont_proj <- storage_container(ad_endp_tok2, "project") 
#df <- storage_read_csv(cont_proj, "who_lives/2022/inputs/WhoLives_longer.csv") %>% select(-1) #make sure this is updated within datalake - querying_WhoLives_factconsolidated

#to write back to azure, use storage_write_csv(df, cont_proj, "who_lives/2022/outputs/file_name")
