library(censusapi) 
library(tidyverse)
library(dplyr)
library(extrafont)
library(scales)
library(directlabels)
library(grid)
library(here)
library(knitr)
library(readxl)
library(xfun)

#HT created this in the 2024 who lives to be a crosswalk to the Louisiana and US design factors to calculate error for the 2000's data in the wholivesdatapull2000 in the functions.R file.
Census2000_designfac <- read_xlsx("inputs/2000_census/Census2000SF3_designfac.xlsx")

#load("inputs/allparishesRawx.RData")

library(AzureAuth) ## to connect with credentials
library(AzureStor) ## to access the stored data

## install azure cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
## sign in to Azure using your AAD un/pw in the terminal/commandline: az login 
## get token in terminal/commandline: az account get-access-token --resource https://datacenterdc2datalake.blob.core.windows.net/

### define your token 

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ikg5bmo1QU9Tc3dNcGhnMVNGeDdqYVYtbEI5dyIsImtpZCI6Ikg5bmo1QU9Tc3dNcGhnMVNGeDdqYVYtbEI5dyJ9.eyJhdWQiOiJodHRwczovL2RhdGFjZW50ZXJkYzJkYXRhbGFrZS5ibG9iLmNvcmUud2luZG93cy5uZXQvIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2LyIsImlhdCI6MTcyNzEwODE1OSwibmJmIjoxNzI3MTA4MTU5LCJleHAiOjE3MjcxMTIzNTQsImFjciI6IjEiLCJhaW8iOiJBWlFBYS84WEFBQUEvYVhTWWc4Wk1PZ3UxZTRFL3EyQVJMa3lkSXhHWFZxSDZhUkovNTZTc1Y3UjJhcitVMkdGa3BXNGVOcFJLcjlYN21oOFBqbkY0eEIwRFJDa2YzZnZVMU9wTE5VVWFHRUd5K1p5alZHQjZlSXlVQzBVZkxxS216a0RmbHRHb1FSMGNveVU1SGpyeUZDN3ZlaXV4WEE3TVNrYm5COFo1dTdzMjdXWXhXOGFOdCtVUkowZFhiQU5MOVZLUFFmT3lJTCsiLCJhbXIiOlsicnNhIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZGV2aWNlaWQiOiI5ZDI5YThkNi1kNzUzLTQzOGUtYmJhMS1iNzVkZDZkOTI1NDIiLCJmYW1pbHlfbmFtZSI6Ikh5ZGUiLCJnaXZlbl9uYW1lIjoiQW5pc3NhIiwiZ3JvdXBzIjpbImFkMDk0OGFjLWFmNjgtNDQ5NS04Y2NkLTQxNGMzY2NmZjM3MyJdLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyMDguMTE3LjIwNy4xMjIiLCJuYW1lIjoiQW5pc3NhIEh5ZGUiLCJvaWQiOiI4OWE0NTBmNy04MTkwLTQxMDktYWIxNC0wNTdmNWE1YzJjYTYiLCJwdWlkIjoiMTAwMzIwMDM5ODc2NUMyNiIsInB3ZF91cmwiOiJodHRwczovL3BvcnRhbC5taWNyb3NvZnRvbmxpbmUuY29tL0NoYW5nZVBhc3N3b3JkLmFzcHgiLCJyaCI6IjAuQVNrQXVoLWNkQ2tzRDBxSDJvZDJSN3U5aG9HbUJ1VFU4NmhDa0xiQ3NDbEpldkVwQU9jLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6IkplMG5qSUEzOElHdkdUM2RVd1BSRG5uWUJVR2UweUJsNG1kMGk0MlczTkkiLCJ0aWQiOiI3NDljMWZiYS0yYzI5LTRhMGYtODdkYS04Nzc2NDdiYmJkODYiLCJ1bmlxdWVfbmFtZSI6ImFuaXNzYWhAZGF0YWNlbnRlcnJlc2VhcmNoLm9yZyIsInVwbiI6ImFuaXNzYWhAZGF0YWNlbnRlcnJlc2VhcmNoLm9yZyIsInV0aSI6ImEtenYzaGZtUDBxWWYxZGZDTTQ5QUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfaWRyZWwiOiIyMiAxIn0.P67FQ9Lu9ToU6BN0MVNHHF4C88VrZHmVLob9AJRLUcDdZZiJsmouYbSdHuC27xmomy_SNPuPLP9OBsnJguIhk4b0jANwIFrLGuDTfhLjZrZ0AmfBMEo9YgK9VUQeG086WXFG0dTZ2lI6SY41tgyAZ7sCW5nKAuTM7cj58CqMq1_NfiPTV9x7UaC8DgO3drKCtdsv3N44QHH7kPoahXcQOZiQXZwIj5h_iq_Qx7nZvcsjoJvBOIrzIU7g-2CjwhZ7He5wK-z6tTeIW7qJzjjIUh3cs8yLNKUbb9fXqI1adIC8asjQ4J_uOM9m3q2t9akwAaQlSNWJAGe-xNo_0RlIbQ"

ad_endp_tok2 <- storage_endpoint("https://datacenterdc2datalake.blob.core.windows.net/", token=token) ## again, the rsource/URL

## Connections to some most-used containers.
cont_proj <- storage_container(ad_endp_tok2, "project") 
#df <- storage_read_csv(cont_proj, "who_lives/2022/inputs/WhoLives_longer.csv") %>% select(-1) #make sure this is updated within datalake - querying_WhoLives_factconsolidated

#to write back to azure, use storage_write_csv(df, cont_proj, "who_lives/2022/outputs/file_name")
