library(AzureAuth) ## to connect with credentials
library(AzureStor) ## to access the stored data

## install azure cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
## sign in to Azure using your AAD un/pw in the terminal/commandline: az login 
## get token in terminal/commandline: az account get-access-token --resource https://datacenterdc2datalake.blob.core.windows.net/

### define your token 
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2RhdGFjZW50ZXJkYzJkYXRhbGFrZS5ibG9iLmNvcmUud2luZG93cy5uZXQvIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2LyIsImlhdCI6MTY3OTY4MzQxNiwibmJmIjoxNjc5NjgzNDE2LCJleHAiOjE2Nzk2ODc3MjIsImFjciI6IjEiLCJhaW8iOiJBVFFBeS84VEFBQUFUSm8ycHcwOEwwZGZMcFVZWmNiYVVLRHM4Yzg4QitRS254K1JIU2hRek5nOXRvZGR1eURJVHJSSkgyRlV3dDgrIiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiVG9tbGluIiwiZ2l2ZW5fbmFtZSI6IkhhbGVpZ2giLCJncm91cHMiOlsiNzcyYzQ3MWMtZTVkMy00ZWI0LWE2YTEtZGY5ZGVmOTYxZmVjIiwiYWQwOTQ4YWMtYWY2OC00NDk1LThjY2QtNDE0YzNjY2ZmMzczIl0sImlwYWRkciI6IjIwOC4xMTcuMjA3LjEyMiIsIm5hbWUiOiJIYWxlaWdoIFRvbWxpbiIsIm9pZCI6IjE4OTgxMjUzLTQxNjQtNDkyMC1hMWI5LTE5YjA2NzE4MDVmMSIsInB1aWQiOiIxMDAzMjAwMjFFRTAzNjQ3IiwicmgiOiIwLkFTa0F1aC1jZENrc0QwcUgyb2QyUjd1OWhvR21CdVRVODZoQ2tMYkNzQ2xKZXZFcEFIOC4iLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJzdWIiOiJ6OU1xcER5Z1Exb3JhRWdHdHRZUTd6eXY0czFVOWpjcHRQdzUtQkoxZk9nIiwidGlkIjoiNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2IiwidW5pcXVlX25hbWUiOiJIYWxlaWdodEBkYXRhY2VudGVycmVzZWFyY2gub3JnIiwidXBuIjoiSGFsZWlnaHRAZGF0YWNlbnRlcnJlc2VhcmNoLm9yZyIsInV0aSI6IkdyRzViY0ZEM1VhVXI2VVYwM3lsQUEiLCJ2ZXIiOiIxLjAifQ.Cz2dSl88ynEGzLNgWXOv4QwyuuwzEPxMh7Ad80xRaO8KYgEAGALgyASinK5fz2BFxxF64FPz9b5R5fk9mpN4iHPkODl7L_F8EwrTlrprzID4bQPOEgrkrCooFGYXsF1_AKZkpbB2Ahpa9EA4bqXbj-2J5IEnrFlwgXr79nlFuwJ-dELZ-7_YO7HbyVi43XQ5xfUQRgFpI4pYAQJLiTj6fVauflLpHjVz1qywHvJxYWQ2Ori4-D3nrlxaJ7CHnNrqT8YxNa_lXNb4cQjBdICGrB53txFhsdB4ty3OptLyx9XzkVChBFlkkQB9i2S8oows3XSabL3o5r0Hf8pZRlqiUw"
# delete token before pushing to github

ad_endp_tok2 <- storage_endpoint("https://datacenterdc2datalake.blob.core.windows.net/", token=token) ## again, the rsource/URL

## Connections to some most-used containers.
cont_proj <- storage_container(ad_endp_tok2, "project") 
df <- storage_read_csv(cont_proj, "who_lives/2022/inputs/WhoLives_longer.csv") %>% select(-1) #make sure this is updated within datalake - querying_WhoLives_factconsolidated

#to write back to azure, use storage_write_csv(df, cont_proj, "who_lives/2022/outputs/file_name")