library(AzureAuth) ## to connect with credentials
library(AzureStor) ## to access the stored data

## install azure cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
## sign in to Azure using your AAD un/pw in the terminal/commandline: az login 
## get token in terminal/commandline: az account get-access-token --resource https://datacenterdc2datalake.blob.core.windows.net/

### define your token 
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyIsImtpZCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyJ9.eyJhdWQiOiJodHRwczovL2RhdGFjZW50ZXJkYzJkYXRhbGFrZS5ibG9iLmNvcmUud2luZG93cy5uZXQvIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2LyIsImlhdCI6MTcxOTUxNjk5MCwibmJmIjoxNzE5NTE2OTkwLCJleHAiOjE3MTk1MjA5MzAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WEFBQUEzQVRFY2dRN25CYXdab2M4Zm1VS3grRFRrSCtaOUFOSDdDQml6VmNpaUt6aEYxWU1pdUVWUmZ1S2lJZkpiR3AxS21oR1YzTUFETzBsN05URzc0UkpsK2h5K25LQysyTU43bUhCcy9HeUljST0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJUb21saW4iLCJnaXZlbl9uYW1lIjoiSGFsZWlnaCIsImdyb3VwcyI6WyI3NzJjNDcxYy1lNWQzLTRlYjQtYTZhMS1kZjlkZWY5NjFmZWMiLCJhZDA5NDhhYy1hZjY4LTQ0OTUtOGNjZC00MTRjM2NjZmYzNzMiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjA4LjExNy4yMDcuMTIyIiwibmFtZSI6IkhhbGVpZ2ggVG9tbGluIiwib2lkIjoiMTg5ODEyNTMtNDE2NC00OTIwLWExYjktMTliMDY3MTgwNWYxIiwicHVpZCI6IjEwMDMyMDAyMUVFMDM2NDciLCJyaCI6IjAuQVNrQXVoLWNkQ2tzRDBxSDJvZDJSN3U5aG9HbUJ1VFU4NmhDa0xiQ3NDbEpldkVwQUg4LiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ino5TXFwRHlnUTFvcmFFZ0d0dFlRN3p5djRzMVU5amNwdFB3NS1CSjFmT2ciLCJ0aWQiOiI3NDljMWZiYS0yYzI5LTRhMGYtODdkYS04Nzc2NDdiYmJkODYiLCJ1bmlxdWVfbmFtZSI6IkhhbGVpZ2h0QGRhdGFjZW50ZXJyZXNlYXJjaC5vcmciLCJ1cG4iOiJIYWxlaWdodEBkYXRhY2VudGVycmVzZWFyY2gub3JnIiwidXRpIjoiXzZVRkJJRFZPRUN6SGE1aGhqRXlBUSIsInZlciI6IjEuMCIsInhtc19pZHJlbCI6IjYgMSJ9.kfxnW65ia4F9gBuuZkdnyaRYnAeiZFKCeh3R_Yfiz235Tuy1TfWjyJW-m37377c2CYCtb-rfB-QJxI69_UW7BTRyuAs4SA7EhLGXzPrZdfW_HDC0X2AKw8Ed5ha6CBT2FsGnfrrAqtylIARiuNbKKsuYSo_JQxvPoMe6AiQBzPGMN9W1Zu-Wt67sEv_o4jZMPqzZbwWVg48nN5jz0ei3g2Dpsg-Th3_KKP-xmGQyYH1oGmvIhIYiI9pr29XEfGiVi2Q8akqG0ym3ejUJ1_r5GcAnbY9PpGcDiu1b0i07GpM6F8fc3zmtWp9bxucIeRPeqy18bCbTbxKy3W88bPBC1A"
# delete token before pushing to github

ad_endp_tok2 <- storage_endpoint("https://datacenterdc2datalake.blob.core.windows.net/", token=token) ## again, the rsource/URL

## Connections to some most-used containers.
cont_proj <- storage_container(ad_endp_tok2, "project") 
#df <- storage_read_csv(cont_proj, "who_lives/2022/inputs/WhoLives_longer.csv") %>% select(-1) #make sure this is updated within datalake - querying_WhoLives_factconsolidated

#to write back to azure, use storage_write_csv(df, cont_proj, "who_lives/2022/outputs/file_name")