library(AzureAuth) ## to connect with credentials
library(AzureStor) ## to access the stored data

## install azure cli: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli
## sign in to Azure using your AAD un/pw in the terminal/commandline: az login 
## get token in terminal/commandline: az account get-access-token --resource https://datacenterdc2datalake.blob.core.windows.net/

### define your token 
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2RhdGFjZW50ZXJkYzJkYXRhbGFrZS5ibG9iLmNvcmUud2luZG93cy5uZXQvIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzQ5YzFmYmEtMmMyOS00YTBmLTg3ZGEtODc3NjQ3YmJiZDg2LyIsImlhdCI6MTY5NjAwNzM4MywibmJmIjoxNjk2MDA3MzgzLCJleHAiOjE2OTYwMTI0NzksImFjciI6IjEiLCJhaW8iOiJBVlFBcS84VUFBQUFZMkFFMUhNVHBqKzFFMFBITGJFRUlnNVc3SEhxV21LV3pHWkc2US8yY0NxQkwxMlQxdmxLZmsya1BqTVRNVEdLR2pyaHAvNG1kcjZKMENpbkZrOVAvNjcweHNOckNtbzhkY25sWjNCVExGYz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJUb21saW4iLCJnaXZlbl9uYW1lIjoiSGFsZWlnaCIsImdyb3VwcyI6WyI3NzJjNDcxYy1lNWQzLTRlYjQtYTZhMS1kZjlkZWY5NjFmZWMiLCJhZDA5NDhhYy1hZjY4LTQ0OTUtOGNjZC00MTRjM2NjZmYzNzMiXSwiaXBhZGRyIjoiMjA4LjExNy4yMDcuMTIyIiwibmFtZSI6IkhhbGVpZ2ggVG9tbGluIiwib2lkIjoiMTg5ODEyNTMtNDE2NC00OTIwLWExYjktMTliMDY3MTgwNWYxIiwicHVpZCI6IjEwMDMyMDAyMUVFMDM2NDciLCJyaCI6IjAuQVNrQXVoLWNkQ2tzRDBxSDJvZDJSN3U5aG9HbUJ1VFU4NmhDa0xiQ3NDbEpldkVwQUg4LiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6Ino5TXFwRHlnUTFvcmFFZ0d0dFlRN3p5djRzMVU5amNwdFB3NS1CSjFmT2ciLCJ0aWQiOiI3NDljMWZiYS0yYzI5LTRhMGYtODdkYS04Nzc2NDdiYmJkODYiLCJ1bmlxdWVfbmFtZSI6IkhhbGVpZ2h0QGRhdGFjZW50ZXJyZXNlYXJjaC5vcmciLCJ1cG4iOiJIYWxlaWdodEBkYXRhY2VudGVycmVzZWFyY2gub3JnIiwidXRpIjoiQVdZM1ZURzhnMHE2S2RGcVlZQjFBQSIsInZlciI6IjEuMCJ9.qYoxIxRJOLPdnS0Vutj9hLcp7whzwW58g03El87bEUImDRqLJ4og2k8NfHk2PGEPBSPK4Lk9GBzDgP5lLXny_dU7f_IbxUTKIzHSGD7z-Q8D0FdOD94PczsQK0ldg9RUQ5CvauC7eO2S5PClsFA7sCtZd8ObGDy-Wm7GoljqLuKD7ujdlRt2BoaE6dtSGx1pjXEdhDaGw13xSaaJgBX8c7Nidx1vW8bRC4_DE4TN-Lnp6nIyx2V1Md8TAmZabl3sAc9DE2-Z3CDeEABNR9XW-9Y8ZMOFFGzhsqqY2YoL9plYLkx_JAJ6H3B2tDfENOrSZ4bYtIhIoDqPPe57xuprSg"
# delete token before pushing to github

ad_endp_tok2 <- storage_endpoint("https://datacenterdc2datalake.blob.core.windows.net/", token=token) ## again, the rsource/URL

## Connections to some most-used containers.
cont_proj <- storage_container(ad_endp_tok2, "project") 
df <- storage_read_csv(cont_proj, "who_lives/2022/inputs/WhoLives_longer.csv") %>% select(-1) #make sure this is updated within datalake - querying_WhoLives_factconsolidated

#to write back to azure, use storage_write_csv(df, cont_proj, "who_lives/2022/outputs/file_name")